language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: fc35df7183cdab917add7362c2bcd73ad37a9087d240ce0b8d7cd89b3b51fef6
script: npm run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
