language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: BOOP
script: npm run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
